version: '3.8'

services:
# Production Environment - React App  
  react-app-prod:
    image: alexalphonse/devops-build-prod:latest
    ports:
      - "80:80"
    container_name: react-app-prod
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
